### PR TITLE
Ignore trailing sleeping samples for duration estimation

### LINKED ISSUE #411: Profiler "only ticks over" might be working incorrectly
### Description

I was following guide https://spark.lucko.me/docs/guides/Finding-lag-spikes

And was trying to find all ticks that making tps < 20. 
My understanding that ticks longer than 50ms should be problematic to tps, so I run profiler with next command:
`/spark profiler --only-ticks-over 50`

Result that I got said that
The profiler was running for 4m 50s (5790 ticks). 2919 ticks exceeded the 'only ticks over' threshold.
Which is ~50% of all ticks.
But at the same time in top left corner it shows 
TPS 20.00 1m
MSPT 0.676 min | 4.43 med | 8.39 95%ile | 143 max
So if I read it correctly I should have for sure less than 5% of my ticks over threshold, if like 95% around 8ms (which is less than 50 that I set).

Versions and other logs are available in report.
Spark 1.10.58-fabric
https://spark.lucko.me/aDdpCEu3HR

### Reproduction Steps

1. `/spark profiler --only-ticks-over 50` 
2. `/spark profiler stop`

### Expected Behaviour

I expect to get less items in log

### Platform Information

* Minecraft Version: 1.20.4
* Platform Type: server
* Platform Brand: Fabric
* Platform Version: 0.15.11

### Spark Version

1.10.58-fabric

### Logs and Configs

https://spark.lucko.me/aDdpCEu3HR

### Extra Details

Additional log, same issue
https://spark.lucko.me/d7SPNUKIUO

### PR DESCRIPTION
**Pull request by SirYwell**
Fixes #411.

Currently, the `--only-ticks-over` option does not work as expected for  values <`50ms + interval`. This comes from the fact that the sampler collects *all* samples from the current tick to estimate the tick duration, even if it's sleeping for most of the time.

By filtering out the trailing sleeping samples, we get a more precise estimation of the actual tick time.

### Alternatives

An alternative implementation could make use of the `TickReporter` to get the actually measured tick duration. However, this is more invasive and requires additional changes to remove the `TickReporter.Callback` once the `JavaDataAggregator` is not needed anymore to avoid memory leaks.

### CODE REVIEW

File: spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java [hunk 1]
```diff
@@ -151,6 +151,17 @@ public List<ThreadInfo> getList() {
             return this.list;
         }
 
+        public int sizeWithoutTrailingSleeping() {
+            // find the last index at which the thread wasn't sleeping
+            int i;
+            for (i = this.list.size() - 1; i >= 0; i--) {
+                if (!isSleeping(this.list.get(i))) {
+                    return i;
```
Comment (lucko) [inline spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java:159]: I think this should probably return `i + 1` because initially `i` is set to `this.list.size() - 1`?

File: spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java [hunk 2]
```diff
@@ -151,6 +151,17 @@ public List<ThreadInfo> getList() {
             return this.list;
         }
 
+        public int sizeWithoutTrailingSleeping() {
```
Comment (lucko) [inline spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java:154]: Is there a reason this method uses `this.list` instead of `currentData.getList()` (could pass it as a parameter?)

**Review by lucko — CHANGES_REQUESTED** [review]

File: spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java (hunk 2 above)
Comment (SirYwell) [reply spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java:154]: I just put the method into `TickList`, but there isn't much thought to it. I can also move it to the enclosing class if you want.

Comment (lucko) [reply spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java:154]: Ahhh doh, sorry I misread - it's good how it is :)

File: spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java (hunk 1 above)
Comment (SirYwell) [reply spark-common/src/main/java/me/lucko/spark/common/sampler/java/TickedDataAggregator.java]: Fixed

**Review by lucko — APPROVED** [review]

**Comment by lucko** [comment]
thanks :)
